#!/usr/bin/env python3
"""Generate src/tokenizer/unicode_ranges.h — sorted codepoint ranges for the
three character classes the Qwen2 pre-tokenizer regex needs: \\p{L} (letter),
\\p{N} (number), and \\s (whitespace).

Derivation (auditable, self-contained — NOT copied from llama.cpp):
  - LETTER  : unicodedata.category(cp) starts with 'L'  (Lu Ll Lt Lm Lo)
  - NUMBER  : unicodedata.category(cp) starts with 'N'  (Nd Nl No)
  - WHITESPACE : the `regex` module's own \\s match — keeps C parity with the
    validated bpe_proto.py prototype, which used `regex`.

Run from the engine repo root:  python -X utf8 tools/oracle/gen_unicode_tables.py
This is a build-time generator; the emitted header is committed.
"""
import sys, unicodedata, regex as re

MAXCP = 0x110000

def ranges(pred):
    out = []
    start = None
    for cp in range(MAXCP):
        if pred(cp):
            if start is None: start = cp
        else:
            if start is not None: out.append((start, cp - 1)); start = None
    if start is not None: out.append((start, MAXCP - 1))
    return out

def is_letter(cp): return unicodedata.category(chr(cp)).startswith('L')
def is_number(cp): return unicodedata.category(chr(cp)).startswith('N')
_ws = re.compile(r'\s')
def is_space(cp):  return _ws.match(chr(cp)) is not None

def emit(f, name, rs):
    f.write(f"static const uint32_t {name}[][2] = {{\n")
    for a, b in rs:
        f.write(f"    {{0x{a:04X}, 0x{b:04X}}},\n")
    f.write("};\n")
    f.write(f"static const size_t {name}_n = {len(rs)};\n\n")

def main():
    L = ranges(is_letter); N = ranges(is_number); S = ranges(is_space)
    with open("src/tokenizer/unicode_ranges.h", "w", encoding="utf-8", newline="\n") as f:
        f.write("/* unicode_ranges.h — GENERATED by tools/oracle/gen_unicode_tables.py.\n"
                " * Do not edit by hand. Sorted [lo,hi] codepoint ranges for the Unicode\n"
                " * character classes the Qwen2 pre-tokenizer needs (\\p{L}, \\p{N}, \\s).\n"
                " * Derived from Python unicodedata + the `regex` module (see generator);\n"
                " * self-contained, not copied from llama.cpp. Binary-searched in tokenizer.c. */\n"
                "#ifndef SP_ENGINE_UNICODE_RANGES_H\n#define SP_ENGINE_UNICODE_RANGES_H\n"
                "#include <stdint.h>\n#include <stddef.h>\n\n")
        emit(f, "sp_uni_letter", L)
        emit(f, "sp_uni_number", N)
        emit(f, "sp_uni_space",  S)
        f.write("#endif /* SP_ENGINE_UNICODE_RANGES_H */\n")
    print(f"letter ranges={len(L)} number ranges={len(N)} space ranges={len(S)}")

if __name__ == "__main__":
    main()
