//! Raw bindgen-generated FFI bindings to the frozen L1 C ABI (sp_l1.h).
//! Do not hand-edit — regenerated by build.rs on each header change.
#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]
include!(concat!(env!("OUT_DIR"), "/sp_bindings.rs"));
